### ISSUE TITLE
Error when running eda configure default

### ISSUE THREAD

**Issue by jehart15** [jschnab/easy-data-analysis#10]
```Jaynees-MBP:~ jayneehart$ eda configure default
Traceback (most recent call last):
  File "/usr/local/bin/eda", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/eda/cli.py", line 298, in main
    CliParser()
  File "/usr/local/lib/python3.7/site-packages/eda/cli.py", line 32, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.7/site-packages/eda/cli.py", line 49, in configure
    config = ConfigurationManager()
  File "/usr/local/lib/python3.7/site-packages/eda/configure.py", line 31, in __init__
    copyfile(self.config_default, self.config_user)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/eda/config_default.yaml'```

**Comment by jschnab** [comment]
Thanks for reporting, working on it.
